name: at_location_flutter
description: A flutter plugin project to share location between two atsigns and track them on OSM (open street maps).
version: 0.0.2
homepage: https://atsign.com/

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  tuple: ^1.0.2
  latlong: ^0.6.1
  positioned_tap_detector: ^1.0.2
  transparent_image: ^1.0.0
  async: ^2.1.0
  flutter_image: ^3.0.0
  cached_network_image: ^2.0.0
  path_provider: ^1.6.7
  vector_math: ^2.0.0
  proj4dart: ^1.0.4
  meta: ^1.1.0
  geolocator: ^6.2.1
  toast: ^0.1.5
  sliding_up_panel: ^1.0.2
  http: ^0.12.2
  crypto: ^2.1.5

  at_client_mobile: ^1.0.0+5
  at_lookup: ^1.0.0+3
  at_commons: ^1.0.1+4
  at_contact: ^1.0.0
  at_common_flutter: ^0.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # This section identifies this Flutter project as a plugin project.
  # The 'pluginClass' and Android 'package' identifiers should not ordinarily
  # be modified. They are used by the tooling to maintain consistency when
  # adding or updating assets for this project.
  plugin:
    platforms:
      android:
        package: com.atsign.at_location_flutter
        pluginClass: AtLocationFlutterPlugin
      ios:
        pluginClass: AtLocationFlutterPlugin

  # To add assets to your plugin package, add an assets section, like this:
  assets:
    - packages/at_location_flutter/assets/images/empty_group.png

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # To add custom fonts to your plugin package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
