name: at_follows_flutter
description: A new flutter plugin project to integrate follows functionality for any @sign. Provides list of followers, following and options to follow, unfollow any @sign.
version: 1.0.0+2
homepage: https://atsign.dev
repository: https://github.com/atsign-foundation/at_widgets

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^5.0.0
  flutter_qr_reader: ^1.0.3
  permission_handler: ^6.1.3
  webview_flutter: ^2.0.4
  url_launcher: ^6.0.3
  at_utils:
    git:
      url: https://github.com/atsign-foundation/at_tools.git
      path: at_utils
      ref: trunk
      version: ^1.0.1+7
  at_client_mobile:
    git:
      url: https://github.com/atsign-foundation/at_client_sdk.git
      path: at_client_mobile
      ref: trunk
      version: ^1.0.0+10
  at_server_status:
    git:
      url: https://github.com/atsign-foundation/at_libraries.git
      path: at_server_status
      ref: trunk
      version: ^0.1.0+1
  at_commons:
    git:
      url: https://github.com/atsign-foundation/at_tools.git
      path: at_commons
      ref: trunk
      version: ^1.0.1+7
  at_lookup:
    git:
      url: https://github.com/atsign-foundation/at_libraries.git
      path: at_lookup
      ref: trunk
      version: ^1.0.0+7


dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # This section identifies this Flutter project as a plugin project.
  # The 'pluginClass' and Android 'package' identifiers should not ordinarily
  # be modified. They are used by the tooling to maintain consistency when
  # adding or updating assets for this project.
  plugin:
    platforms:
      android:
        package: com.atsign.at_follows_flutter
        pluginClass: AtFollowsFlutterPlugin
      ios:
        pluginClass: AtFollowsFlutterPlugin

  # To add assets to your plugin package, add an assets section, like this:
  assets:
    - assets/images/
    - assets/jsons/
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # To add custom fonts to your plugin package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
